import DashboardIcon from "@mui/icons-material/Dashboard";
import ListIcon from "@mui/icons-material/List";
import TableViewIcon from "@mui/icons-material/TableView";
import SettingsIcon from "@mui/icons-material/Settings";
import LogoutIcon from "@mui/icons-material/Logout";
import UploadIcon from "@mui/icons-material/Upload";
import DownloadIcon from "@mui/icons-material/Download";
import DeleteIcon from "@mui/icons-material/Delete";
import VisibilityIcon from "@mui/icons-material/Visibility";
import EditIcon from "@mui/icons-material/Edit";

export const Dashboard = (props) => <DashboardIcon {...props} />;
export const Master = (props) => <ListIcon {...props} />;
export const Table = (props) => <TableViewIcon {...props} />;
export const Setting = (props) => <SettingsIcon {...props} />;
export const Logout = (props) => <LogoutIcon {...props} />;
export const Upload = (props) => <UploadIcon {...props} />;
export const Download = (props) => <DownloadIcon {...props} />;
export const Delete = (props) => <DeleteIcon {...props} />;
export const Detail = (props) => <VisibilityIcon {...props} />;
export const Edit = (props) => <EditIcon {...props} />;
